services:
  - type: web
    name: digifinwiz
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ALLOWED_ORIGIN
        value: "https://loquacious-pie-f7ae65.netlify.app"
    autoDeploy: true
